version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = '   {{ .Path }} '
    background = 'p:blue'
    foreground = 'p:black'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}', '{{ if gt .Ahead 0 }}p:white{{ end }}']
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}#49416D{{ end }}', '{{ if gt .Behind 0 }}#7A306C{{ end }}']
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    background = 'p:green'
    foreground = 'p:black'

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = '  '
    background = 'p:yellow'
    foreground = 'p:white'

[[blocks]]
  type = 'rprompt'

[[tooltips]]
  type = 'aws'
  tips = ['aws']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  background = 'p:orange'
  foreground = 'p:white'

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'az'
  tips = ['az']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = '  {{ .Name }} '
  background = 'p:blue'
  foreground = 'p:white'

  [tooltips.properties]
    display_default = true

[[tooltips]]
  type = 'kubectl'
  tips = ['kubectl']
  style = 'diamond'
  leading_diamond = ''
  trailing_diamond = ''
  template = ' ﴱ {{.Context}}{{if .Namespace}} :: {{.Namespace}}{{end}} '
  background = 'p:blue'
  foreground = 'p:white'

  [tooltips.properties]
    display_default = true


[transient_prompt]
  template = '<p:blue,transparent></><,p:blue>   {{ .Folder }} </><p:blue,transparent></> '
  background = 'transparent'
  foreground = 'p:black'
  newline = true

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
